OSSystems/meta-browser

- recipes-mozilla/firefox-addon/firefox-addon.inc
- recipes-mozilla/firefox-l10n/firefox-l10n.inc
As the title says. A little embarrassed that I missed this.
> Fix checksums missed in Firefox 38.6.1esr update.

- recipes-browser/chromium/chromium.inc
- recipes-browser/chromium/files/aarch64/include.gypi
- recipes-browser/chromium/files/aarch64/oe-defaults.gypi
Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>
> chromium: enable aarch64 support

- recipes-browser/chromium/chromium-wayland_53.0.2785.143.bb
- recipes-browser/chromium/chromium.inc
- recipes-browser/chromium/chromium/chromium-wayland/remove-armv7-a-from-options.patch
- recipes-browser/chromium/files/armv7ve/include.gypi
> chromium-wayland: Fix build on armv7ve/rpi3

- recipes-browser/chromium/chromium-browser.inc
- recipes-browser/chromium/files/0001-openh264-disable-format-security-warning.patch.patch
- recipes-browser/chromium/files/0002-replace-struct-ucontext-with-ucontext_t.patch
Also fix build with glibc 2.26 while here
> chromium: Fix build with security flags

- recipes-mozilla/firefox/firefox/remove_AC_PATH_XTRA.patch
- recipes-mozilla/firefox/firefox_45.9.0esr.bb
> firefox: Fix Build QA error compile-host-path

- recipes-browser/chromium/chromium-browser.inc
> chromium-browser.inc: Fix typo in variable name for USEGOLD

- recipes-browser/chromium/chromium-browser.inc
- recipes-browser/chromium/chromium.inc
Another easy part of the road to M62.
This pull request contains some actual bug fixes that apply to the existing M54 recipe. They're not really related to each other, but I figured it'd be good to land all fixes together.
See also: #62.
> chromium: Small, assorted bug fixes.

- recipes-browser/chromium/chromium-x11_67.0.3396.87.bb
- recipes-browser/chromium/files/0001-Fix-operator-bool-in-AssociatedInterfacePtrInfo-and-.patch
> chromium-x11: Import patch to fix the build with GCC 8

- README
- conf/layer.conf
> Add dependency on meta-rust

- recipes-browser/firefox/firefox/musl/fix-bug-1261392.patch
- recipes-browser/firefox/firefox/musl/musl-mutex.patch
- recipes-browser/firefox/firefox/musl/musl-tools-fix.patch
- recipes-browser/firefox/firefox/musl/musl_webrtc_glibcism.patch
- recipes-browser/firefox/firefox_60.1.0esr.bb
Add patches from Alpine Linux to get it building on musl targets
> firefox: Fix build with musl

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/chromium-ozone-wayland_72.0.3626.121.bb
- recipes-browser/chromium/chromium-x11_72.0.3626.121.bb
- recipes-browser/chromium/files/musl/musl-include-fcntl.h-for-loff_t.patch
- recipes-browser/chromium/files/musl/musl_TEMP_FAILURE_RETRY.patch
- recipes-browser/chromium/files/musl/musl_breakpad.patch
- recipes-browser/chromium/files/musl/musl_crashpad.patch
- recipes-browser/chromium/files/musl/musl_fix-stack.patch
- recipes-browser/chromium/files/musl/musl_fontconfig.patch
- recipes-browser/chromium/files/musl/musl_gnu_libc-version.patch
- recipes-browser/chromium/files/musl/musl_libc_malloc.patch
- recipes-browser/chromium/files/musl/musl_lss-match_syscalls.patch
- recipes-browser/chromium/files/musl/musl_no_execinfo.patch
- recipes-browser/chromium/files/musl/musl_no_mallinfo.patch
- recipes-browser/chromium/files/musl/musl_off64_t.patch
- recipes-browser/chromium/files/musl/musl_replace_libc_fpstate.patch
- recipes-browser/chromium/files/musl/musl_resolver.patch
- recipes-browser/chromium/files/musl/musl_secure_getenv.patch
Enable world build for chromium/musl again
> chromium: Fix chromium build with musl again

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/musl/musl_fix_stack_trace.patch
- recipes-browser/chromium/files/musl/musl_no_execinfo.patch
Add a build fix needed for clang/musl
> chromium: Forward port musl patches

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-Avoid-pure-virtual-crash-destroying-RenderProcessUse.patch
This fix contains an upstream fix of the issue.
Issue: #272
> chromium: fix "pure virtual method called" problem.

- README
Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>
> README: update list of maintainers

- recipes-browser/chromium/chromium-gn.inc
This should work on thud and warrior as well. It should speed up linking
> Switch to gold linker as default

- conf/layer.conf
> layer.conf: Mark layer 3.1 release compatible

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/chromium-Move-CharAllocator-definition-to-a-header-f.patch
- recipes-browser/chromium/files/include_string.patch
- recipes-browser/chromium/files/std_size_t.patch
- recipes-browser/chromium/files/stdint.patch
Thanks @kraj  for the original patch.
> chromium: fix building with clang 10

- conf/layer.conf
This is the current Yocto/OE master branch.
> Add "gatesgarth" to LAYERSERIES_COMPAT.

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0007-Add-missing-include-stdint.h.patch
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
> chromium: Add missing include to fix build in oe-master environment

- meta-chromium/recipes-browser/chromium/chromium.inc
Depends on https://github.com/OSSystems/meta-browser/pull/470
> chromium: remove dependency on target python

- meta-chromium/conf/layer.conf
- meta-firefox/conf/layer.conf
Depends on https://github.com/OSSystems/meta-browser/pull/470
> layer.conf: update LAYERSERIES_COMPAT for hardknott

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/musl/0018--Use-monotonic-clock-for-pthread_cond_timedwait-with-.patch
- meta-chromium/recipes-browser/chromium/files/musl/0019-adjust-thread-stack-sizes.patch
- meta-chromium/recipes-browser/chromium/files/musl/0020-Fix-tab-crashes-on-musl.patch
> chromium: Fix sanbox crashes on musl

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Fixes
https://github.com/OSSystems/meta-browser/issues/541
> chromium: Package crashpad_handler

- meta-chromium/recipes-browser/chromium/chromium.inc
- meta-chromium/recipes-browser/chromium/gn-utils.inc
This should fix issue seen with
https://github.com/OSSystems/meta-browser/pull/551
> chromium: Set LIBCPLUSPLUS to use libc++

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0001-include-utility.h.patch
- meta-chromium/recipes-browser/chromium/files/musl/0001-mallinfo-implementation-is-glibc-specific.patch
- meta-chromium/recipes-browser/chromium/files/musl/0019-adjust-thread-stack-sizes.patch
- meta-chromium/recipes-browser/chromium/files/musl/0020-Fix-tab-crashes-on-musl.patch
- meta-chromium/recipes-browser/chromium/files/musl/fix-narrowing-cast.patch
Latest update created some conflicts in musl patches.
> chromium: Foward port musl patches

- meta-chromium/recipes-browser/chromium/files/0012-chromium-freetype-2.11.patch
> chromium: update typo in a freetype patch

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/musl/0001-mallinfo-implementation-is-glibc-specific.patch
- meta-chromium/recipes-browser/chromium/files/musl/0002-execinfo-implementation-is-glibc-specific.patch
- meta-chromium/recipes-browser/chromium/files/musl/0007-__libc_malloc-is-internal-to-glibc.patch
- meta-chromium/recipes-browser/chromium/files/musl/0008-gnu_libc_version-API-is-glibc-specific.patch
- meta-chromium/recipes-browser/chromium/files/musl/0009-provide-res_ninit-and-nclose-APIs-on-non-glibc-linux.patch
- meta-chromium/recipes-browser/chromium/files/musl/0012-debug-Fix-build-with-musl.patch
- meta-chromium/recipes-browser/chromium/files/musl/0013-socket-initialize-msghdr-in-a-compatible-manner.patch
- meta-chromium/recipes-browser/chromium/files/musl/0018--Use-monotonic-clock-for-pthread_cond_timedwait-with-.patch
- meta-chromium/recipes-browser/chromium/files/musl/0020-Fix-tab-crashes-on-musl.patch
- meta-chromium/recipes-browser/chromium/files/musl/0022-sys-stat.patch
> chromium: Refresh musl patches

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/musl/0009-provide-res_ninit-and-nclose-APIs-on-non-glibc-linux.patch
- meta-chromium/recipes-browser/chromium/files/musl/chromium-95-quiche-include.patch
- meta-chromium/recipes-browser/chromium/files/musl/fix-bits-stdint-intn-include.patch
> chromium: Forward port musl patches to 95.0.4638.69

- meta-chromium/recipes-browser/chromium/chromium.inc
- meta-firefox/recipes-browser/firefox-l10n/firefox-l10n.inc
- meta-firefox/recipes-browser/firefox/firefox_68.9.0esr.bb
> chromium,firefox: Use SPDX naming scheme for LICENSE

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/musl/fstatat64.patch
This fixes a build error on 32bit machines ( beaglebone )
> chromium: Fix build for 32bit arm/musl

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0014-Remove-usage-of-std-binary_function.patch
> chromium: Fix build with clang-15

- meta-chromium/conf/layer.conf
> layers: Add langdale to LAYERSERIES_COMPAT

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0031-Backport-ozone-wayland-Fix-nullptr-deref-in-WaylandW.patch
> chromium: Backport ozone/wayland crash fix

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
based on the DISTRO_FEATURE alsa
> chromium-gn.inc: make alsa configurable

- meta-chromium/conf/layer.conf
- meta-firefox/conf/layer.conf
* oe-core switched to nanbield in: https://git.openembedded.org/openembedded-core/commit/?id=f212cb12a0db9c9de5afd3cc89b1331d386e55f6
> layer.conf: update LAYERSERIES_COMPAT for nanbield

- meta-chromium/recipes-browser/chromium/files/boringssl_no_asm_config.patch
> chromium: Update arm64 boringssl patch for chromium 116

- meta-chromium/README.md
- meta-chromium/conf/layer.conf
See the discussion in https://github.com/OSSystems/meta-browser/issues/789.
> chromium: Update README and dependencies for kirkstone

- meta-chromium/conf/layer.conf
- meta-firefox/conf/layer.conf
OE-Core has switched the master branch to styhead, follow the change.
> layer.conf: set LAYERSERIES_COMPAT to styhead
