OSSystems/meta-browser

- recipes-mozilla/firefox-addon/firefox-addon.inc
- recipes-mozilla/firefox-l10n/firefox-l10n.inc
- recipes-mozilla/firefox/firefox/fixes/Fix-firefox-install-dir.patch
- recipes-mozilla/firefox/firefox_38.6.1esr.bb
Bring all firefox packages in-line to unified installation path at /usr/lib/firefox/* and move the extensions to the proper location so that they are loaded.
* Firefox ESR was installing to /usr/lib/firefox-38.6/ patch baseconfig so that it is /usr/lib/firefox
* firefox-l10n was installing language packs to /usr/lib/firefox/extensions. This is was incompatible with ESR as it was, and incorrect as they need to be in /usr/lib/firefox/browser/extentions
* firefox-addons was doing the same as firefox-l10n
Signed-off-by: Jason Plum <jplum@devonit.com>
> Firefox: update installation paths for ESR,l10n,addons

- recipes-browser/chromium/chromium-browser.inc
The correct dependencies on egl/wayland-egl are set in line 91:
PACKAGECONFIG[use-egl] = ",,virtual/egl virtual/libgles2"
We must not assign "" to the config in order not to break the build.
Currently the 'bitbake chromium' task fails with the following message:
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function do_configure
| Updating projects from gyp files...
| Package egl was not found in the pkg-config search path.
| Perhaps you should add the directory containing `egl.pc'
| to the PKG_CONFIG_PATH environment variable
| No package 'egl' found
| Package wayland-egl was not found in the pkg-config search path.
| Perhaps you should add the directory containing `wayland-egl.pc'
| …
> chromium: Fix build breakage due to egl override

- recipes-browser/chromium/chromium-wayland_48.0.2548.0.bb
This was accidentally removed when the Wayland/X11 split happened.
> chromium-wayland: Add back ozone-wayland component

- recipes-browser/chromium/chromium/chromium/unset-madv-free.patch
- recipes-browser/chromium/chromium_52.0.2743.76.bb
Fix Aw Snap! error when running chromium 52 in Morty with sandbox enabled.
Based on upstream qtwebengine-chromium commit b12ffcd411d4776f7120ccecb3be34344d930d2b
http://code.qt.io/cgit/qt/qtwebengine-chromium.git/commit/?h=49-based&id=b12ffcd411d4776f7120ccecb3be34344d930d2b
Signed-off-by: Michael Davis <michael.davis@essvote.com>
> chromium: Fix ILL_ILLOPN signal in sandbox

- classes/mozilla.bbclass
Current firefox doesn't depend on orbit2.
These dependencies originate from too old code:
http://git.openembedded.org/openembedded/commit/?id=c8e5702127e507e82e6f68a4b8c546803accea9d
> firefox: Remove needless dependency on orbit2 and libidl-native

- recipes-mozilla/firefox/firefox_45.5.1esr.bb
Following libraries aren't specified as PRIVATE_LIBS although they are also built under the private directory:
* liblgpllibs.so
* libmozsqlite3.so
* libbrowsercomps.so
* libclearkey.so"
> firefox: Add some missing items of PRIVATE_LIBS

- recipes-mozilla/firefox/firefox/mozconfig
The recipe requires system-wide nss & nspr but they were not used
because built-in libraries were implicitly enabled. This patch fix
this issue.
Firefox 45ESR requires following versions:
* nss: 3.21.1
* nspr: 4.12
You need krogoth or later to satisfy these version.
> firefox: Use system-wide nss & nspr

- recipes-mozilla/firefox/firefox/mozconfig
Add "--enable-system-cairo" to mozconfig.
Because gtk+ depends on cairo, no need to add it to DEPENDS.
> firefox: Use system-wide cairo instead of built-in one

- recipes-browser/chromium/chromium_52.0.2743.76.bb
- recipes-browser/chromium/files/i586/x86-m32.patch
Build and run tested on qemux86 (i586) and turbot (x86-64).
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
> chromium: add i586 (qemux86) support

- recipes-browser/chromium/chromium-browser.inc
Add '--incognito' to kiosk mode flags to avoid "restore pages?" message in the
event of unplanned power cycles.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
> chromium/chromium-wayland: update kiosk flags

- recipes-browser/chromium/chromium.inc
This is the version with the extra space before ${ARMFPABI} removed
> chromium: fix null pointer dereference in V8 with gcc-6

- recipes-browser/chromium/chromium-browser.inc
- recipes-browser/chromium/chromium.inc
This patch enables the build of ChromeDriver. This comes
in very handy for test automation. More information can
be found here:
https://sites.google.com/a/chromium.org/chromedriver/
Signed-off-by: Daniel Díaz <daniel.diaz@linaro.org>
> chromium: build ChromeDriver

- recipes-browser/chromium/chromium-browser.inc
This was stolen from meta-oe / meson.bbclass - chromium uses ninja for
build too.
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>
> chromium: show progress for do_compile

- recipes-mozilla/firefox/firefox/fix-python-path.patch
Since OE cross compiles we sometimes will  run into this issue
https://bugzilla.mozilla.org/show_bug.cgi?id=1243321
This fix enhances the existing patch to use PYTHON variable
itself to compute the python binary name and uses usr/bin/env
to find it instead of hardcoding it.
> firefox: Fix missing references to hardcoded PYTHON

- recipes-mozilla/firefox/firefox/add-libresolv.patch
- recipes-mozilla/firefox/firefox_45.9.0esr.bb
On x86_64 build system starts to poke into build system libraries
and its especially seen with glibc 2.26 since it has deprecated
certain symbols which are not available in libc
e.g.
/usr/lib/libresolv.so.2: undefined reference to `__res_maybe_init@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
So its linking to libresolv.so from host system is clear due to this error
because its then using libc.so from cross build which is glibc 2.26
and doesnt have that symbol.
Explicilty specify -lresolv on linker cmdline for components where its
needed.
> firefox: Fix host library contamination on x86_64

- recipes-browser/chromium/chromium-browser.inc
Provide a knob USEGOLD however to enable it if desired
Cc: Denys Dmytriyenko <denis@denix.org>
> chromium: Do not enforce gold as default linker

- recipes-browser/chromium/chromium.inc
- recipes-browser/chromium/files/armv7ve/include.gypi
- recipes-browser/chromium/files/armv7ve/oe-defaults.gypi
Applying the commit from master into morty to support the raspberry pi devices.
> chromium: add support for 32-bit raspberrypi

- recipes-browser/chromium/chromium/chromium/remove-Werror.patch
Apply a commit to **not** treat warnings as errors.
(cc1plus: all warnings being treated as errors.)
Original commit from: https://github.com/OSSystems/meta-browser/commit/76f46c4dc91523783a0f209d3f77a7a1404956a8 This commit is the parent commit in last pull request that I submitted.
I have compiled through and without any other error.
> chromium: remove more Werror flags

- recipes-browser/chromium/files/aarch64/oe-defaults.gypi
- recipes-browser/chromium/files/armv6/oe-defaults.gypi
- recipes-browser/chromium/files/armv7a/oe-defaults.gypi
- recipes-browser/chromium/files/armv7ve/oe-defaults.gypi
- recipes-browser/chromium/files/x86-64/oe-defaults.gypi
- recipes-browser/chromium/files/x86/oe-defaults.gypi
This variable is required to be unset so that we
can tell the system that we are using a different
newer C++ runtime library than the sysroot which
helps in compiling with clang also
Fixes link errors like
undefined reference to '__atomic_is_lock_free'
> chromium: Disable use_sysroot

- recipes-browser/chromium/chromium-browser.inc
- recipes-browser/chromium/chromium_54.0.2810.2.bb
This is the second step of many towards moving the existing Chromium recipe to M62.
This pull request is also quite simple even though it has more than 1 commit: mostly expanding `DESCRIPTION` and `HOMEPAGE`, switching to an https fetch URL and a few other things that couldn't fit in other categories of changes we need to land.
See also: #62.
> chromium: Minor, assorted recipe improvements.

- README
Now that the Chromium recipe has its own README describing its intricacies,
point to it from the top-level one.
While here, remove a few TODO items that are at least 5-years-old.
See also: #62.
> README: Point to Chromium's README.

- recipes-browser/chromium/README
- recipes-browser/chromium/chromium-browser.inc
- recipes-browser/chromium/chromium.inc
- recipes-browser/chromium/chromium_54.0.2810.2.bb
Clean up the recipe's dependencies: add missing ones, remove others that are redundant and make the whole thing easier to read by merging all DEPENDS lines and having them one per line.
The missing dependencies are actually required for me to manage to build the M54 recipe with Yocto rocko.
See also: #62.
> chromium: Dependency adjustments

- recipes-browser/chromium/chromium-gn.inc
The reason of this change is a failing packing stage due to different naming in PN and explicit
target directory names in install. Some of the files cannot be packed if an explicit destination is not
set. Given that the recipe is named chromium-x11 and the future wayland recipe will be called
chromium-ozone-wayland, default the target packaging naming to just chromium.
Error:
Files/directories were installed but not shipped in any package:
/usr/share/applications
/usr/share/applications/chromium.desktop
/usr/bin/chromium
/usr/lib/chromium/
> chromium: Use explicit destination name in FILES

- recipes-browser/chromium/chromium-x11_62.0.3202.94.bb
As discussed in pull request #77, it makes sense to provide some
compatibility glue for users who were used to just doing "bitbake chromium"
before the recipe got renamed to "chromium-x11".
> chromium-x11: Set PROVIDES="chromium".

- recipes-browser/chromium/README
- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/chromium-ozone-wayland_64.0.3274.0.r517731.igalia.1.bb
Whether to use Jumbo builds or not should be up to each user; while it may
decrease build times, it can require more RAM (it tends to cause problems
for me specifically when using GCC because of the amount of memory it
requires).
Additionally, it's not an Ozone-Wayland-specific setting, so it should've
been in chromium-gn.inc had it been the case.
We now provide a PACKAGECONFIG knob (off by default) to control that.
Signed-off-by: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
> chromium-ozone-wayland: Disable Jumbo builds by default.

- recipes-browser/chromium/chromium-ozone-wayland_64.0.3274.0.r517731.igalia.1.bb
Follow what's done in the chromium-x11 recipe and ensure "wayland" is set in
`DISTRO_FEATURES`.
> chromium-ozone-wayland: Require "wayland" in DISTRO_FEATURES.

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/chromium-ozone-wayland_64.0.3274.0.r517731.igalia.1.bb
- recipes-browser/chromium/chromium-x11_62.0.3202.94.bb
The chromium binary must always be passed `--mus --ozone-platform=wayland`, so
ensure that is always done via `CHROMIUM_EXTRA_ARGS`.
> chromium-ozone-wayland: Hardcode a few command-line arguments.

- recipes-browser/chromium/chromium-gn.inc
The only purpose of the "--start-fullscreen" option is to start Chromium in,
well, full screen mode. It turns out the "--kiosk-mode" does the same
thing and applies some other restrictions ("--start-fullscreen" allows one
to exit full screen mode, "--kiosk-mode" does not, for example).
Since "--start-fullscreen" is essentially a subset of "--kiosk-mode",
passing both on the command line is redundant.
See also:
* https://bugs.chromium.org/p/chromium/issues/detail?id=167430
* https://chromium.googlesource.com/chromium/src/+/64.0.3282.186/chrome/browser/ui/startup/startup_browser_creator_impl.cc#364
> chromium: Stop passing --start-fullscreen with the kiosk-mode PACKAGECONFIG

- recipes-browser/chromium/files/0001-GCC-PlaybackImageProvider-Settings-explicitely-set-c.patch
- recipes-browser/chromium/files/0001-GCC-build-fix-base-Optional-T-requires-the-full-decl.patch
- recipes-browser/chromium/files/0001-GCC-fully-declare-ConfigurationPolicyProvider.patch
Bitbake will now flag patches that require fuzz when applied:
http://lists.openembedded.org/pipermail/openembedded-core/2018-March/148675.html
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10450
Fixup the affected patches.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
> chromium-x11: patch refresh

- recipes-browser/chromium/chromium-x11_66.0.3359.139.bb
Support for musl was dropped altogether in commit 6e5dd35 ("chromium-x11:
Remove musl-related code"), but the dependency on libexecinfo when musl is
used ended up remaining in the recipe.
> chromium-x11: Remove musl-only dependency.

- classes/mozilla.bbclass
--disable-elf-hack option should specify with EXTRA_OECONF overrides.
Always specifying it causes confusion why disable-elf-hack is not effective
such as aarch64 and mips and so on.
Because Elf-hack supports arm, i586, and x86_64.
Other platforms is not supported and ignored such as aarch64(Arm 64bit).
ref: https://dxr.mozilla.org/mozilla-esr45/source/configure.in#7398
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
> firefox: Use --disable-elf-hack option if supported

- recipes-browser/chromium/chromium-x11_67.0.3396.62.bb
- recipes-browser/chromium/files/0001-Ensure-all-targets-build-when-target_arch-arm-and-target_os-linux.patch
- recipes-browser/chromium/files/v8-qemu-wrapper.patch
@rakuco: Please check, if the patch is at the correct position. If you accept, I will close #123. BTW: Kudos for keeping chromium in an excellent condition - you are doing a great job!
> chromium-x11: Fix build for ARM / gcc >= 7 + patch refresh

- recipes-browser/firefox/firefox/0001-use-pkg-config-to-find-nss.patch
- recipes-browser/firefox/firefox/prefs/Don-t-auto-disable-extensions-in-system-directories.patch
- recipes-browser/firefox/firefox/prefs/Set-javascript.options.showInConsole.patch
- recipes-browser/firefox/firefox/remove-needless-windows-dependency.patch
Just touch what is necessary to avoid surprises.
Warning seen:
| ...
| Applying patch remove-needless-windows-dependency.patch
| patching file build/moz.configure/toolchain.configure
| Hunk #1 succeeded at 906 with fuzz 2 (offset 32 lines).
| ...
| Applying patch Set-javascript.options.showInConsole.patch
| patching file modules/libpref/init/all.js
| Hunk #1 succeeded at 1232 with fuzz 2 (offset 93 lines).
| ...
| Applying patch Don-t-auto-disable-extensions-in-system-directories.patch
| patching file browser/app/profile/firefox.js
| Hunk #1 succeeded at 62 with fuzz 2 (offset -12 lines).
| ...
| Applying patch 0001-use-pkg-config-to-find-nss.patch
| patching file old-configure
| Hunk #1 succeeded at 10639 with fuzz 2 (offset 1 line).
| Hunk #2 succeeded at 10648 (offset 1 line).
| ... …
> firefox: refresh patches

- recipes-browser/chromium/chromium-gn.inc
So far "pkg-config" was being used both for host and target toolchains; in
practice this meant we would end up passing directories belonging to the
target sysroot when compiling things for the host side.
This has not caused any actual build issues, but it is definitely wrong.
> chromium: Use pkg-config-native when building code on the host.

- recipes-browser/firefox-l10n/firefox-l10n.inc
- recipes-browser/firefox/firefox_52.8.0esr.bb
Current firefox is distributed under MPLv2, not MPLv1 and not triple
license.
> firefox: Update LICENSE

- recipes-browser/chromium/chromium-ozone-wayland_64.0.3274.0.r517731.igalia.1.bb
- recipes-browser/chromium/chromium-x11_68.0.3440.106.bb
- recipes-browser/firefox/firefox_52.9.0esr.bb
These recipes don't build for musl, no need to spend
compute cycles
> firefox/chromium: Exclude from musl world builds

- recipes-browser/chromium/chromium-ozone-wayland_64.0.3274.0.r517731.igalia.1.bb
- recipes-browser/chromium/chromium-x11_68.0.3440.106.bb
- recipes-browser/chromium/files/oe-clang-fixes.patch
- recipes-browser/chromium/files/zlib-aarch64.patch
zlib fix is specific to chromium-68, so when ozone port is brought over
to 68+ then we will need to apply that part as well for now its only x11
port which needs it
> chromium: Refactor clang patch to fix chromium-ozone-wayland

- recipes-browser/firefox/firefox_52.9.0esr.bb
> firefox: Use nasm instead of yasm

- recipes-browser/chromium/README
GCC 6 (i.e. pyro and earlier) builds are currently broken on ARM, and a
patch to fix the issue has not been merged in months. Nobody has complained
so far, so it should be safe to say supporting older GCC releases is not
worth the effort.
Fixes #135.
> chromium-x11: Make it clear that we need GCC >= 7.3.1

- recipes-browser/chromium/chromium-ozone-wayland/0001-Exclude-CRC32-define-for-the-Renesas-M3-board.patch
- recipes-browser/chromium/chromium-ozone-wayland/aarch64-skia-build-fix.patch
- recipes-browser/chromium/chromium-ozone-wayland/libdrm-fixes.patch
- recipes-browser/chromium/chromium-ozone-wayland_71.0.3545.0.r589108.igalia.1.bb
This fixes build failures(compile time) however there remains one link
time failure still which is about detecting crc32 support on aarch64
wrongly, this could be OE or cross compile specific. However, these
patch are a progress from compile errors to link time errors.
> chromium-ozone-wayland: Fix build on aarch64

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-Update-asserts-in-mojo-about-int64_t-s-alignment.patch
GCC 8 changed the behavior of alignof() to return the minimum alignment
required by the target ABI, instead of the preferred alignment. On x86, this
means alignof(int64_t) started returning 4 instead of 8, which led to a
build failure like
In file included from ../../mojo/public/c/system/types.h:15,
from ../../mojo/public/c/system/platform_handle.h:16,
from ../../mojo/public/cpp/platform/platform_handle.h:12,
from ../../mojo/public/cpp/platform/platform_channel_endpoint.h:10,
from ../../mojo/core/connection_params.h:11,
from ../../mojo/core/channel.h:15,
from ../../mojo/core/node_channel.h:19,
from ../../mojo/core/node_controller.h:25,
from ../../mojo/core/node_controller.cc:5:
../../mojo/public/c/system/buffer.h:33:42: error: static assertion failed: int64_t has weird alignment …
> chromium: Fix the x86 build with GCC 8.

- recipes-browser/chromium/chromium-gn.inc
There is nothing wrong with LLD itself, but most of the time it is not
present on either the host system (where it is used by default if it's a
x86-64 system using clang) or the target system (as TOOLCHAIN="clang" does
not bring it in).
This fixes errors such as
python "../../build/toolchain/gcc_link_wrapper.py" --output="yocto_native/brotli" -- clang++ -Wl,--fatal-warnings -Wl,--build-id=sha1 -fPIC -Wl,-z,noexecstack -Wl,-z,now -Wl,-z,relro -Wl,-z,defs -Wl,--as-needed -fuse-ld=lld -Wl,--icf=all -Wl,--color-diagnostics -m64 -Wl,-O2 -Wl,--gc-sections -rdynamic -Wl,-rpath-link=yocto_native -Wl,--disable-new-dtags -L/data/src/yocto/poky/build-sumo-raspiberrypi3-clang/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/chromium-x11/70.0.3538.110-r0/recipe-sysroot-native/usr/lib …
> chromium: Explicitly disable linking with LLD

- recipes-browser/chromium/files/0001-Move-the-atspi2-target-to-a-separate-BUILD.gn-file.patch
I forgot to add upstream-status information and a signed-off-by tag to the
patch added in commit 00ecba0 ("chromium-x11: Update to 71.0.3578.80").
> chromium: Add patch information to 0001-Move-the-atspi2-target-to-a-separate-BUILD.gn-file.patch

- recipes-browser/firefox/firefox/fixes/bug1479540-Accept-triplet-strings-with-only-two.patch
- recipes-browser/firefox/firefox_60.1.0esr.bb
The latest nightly rustc emits "aarch64-fuchsia" as the very first target
from `rustc --print target-list` and this blows up configure error:
> 0:00.80   File "/build/ebisu-20190119/build/tmp/work/aarch64-poky-linux/firefox/60.1.0esr-r0/firefox-60.1.0/build/moz.configure/init.configure", line 580, in split_triplet
> 0:00.80     cpu, manufacturer, os = triplet.split('-', 2)
> 0:00.80 ValueError: need more than 2 values to unpack
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
> firefox: Backport the patch to accept "triplet" strings with only two parts

- recipes-browser/chromium/chromium-gn.inc
When using meta-clang, one can use the lld compiler by setting ld-is-lld in DISTRO_FEATURES.
Verified on arm 32bit using master branches of meta-clang, openembedded-core and meta-openembedded.
> Only enable lld when set in DISTRO_FEATURES

- recipes-browser/chromium/chromium-gn.inc
Commit 7c6d7bb ("chromium: enable lld when set in distro features") broke
do_configure() as instead of passing a key=value pair to GN it was just
passing the value half.
Spotted by @diego-santacruz.
> chromium: Fix do_configure() after 7c6d7bb

- recipes-browser/chromium/chromium-gn.inc
Even when building non-component builds, libminigbm.so isn't linked in statically.
So let's check if the library exists and ship it anyways.
> chromium: minigbm doesn't seem to link statically

- classes/mozilla.bbclass
We should specify `--libdir` in mozilla.bbclass
because multilib environment requests to put libraries into
not default location.
(e.g. `/usr/lib64` in x86_64 firefox build on multilib environment case.)
Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>
> firefox: Support multilib environment

- recipes-browser/firefox/firefox_60.4.0esr.bb
Because it doesn't take effect.
"--libdir" is already added to EXTRA_OECONF instead.
> firefox: Remove "installdir"

- recipes-browser/chromium/chromium-ozone-wayland/0001-ozone-wayland-Add-const-keyword-to-getters.patch
- recipes-browser/chromium/chromium-ozone-wayland/0002-ozone-wayland-Clean-up-data-device-related-code.patch
- recipes-browser/chromium/chromium-ozone-wayland/0003-ozone-Allow-running-presentation-feedback-any-time-a.patch
- recipes-browser/chromium/chromium-ozone-wayland/0004-ozone-wayland-Factor-out-zwp-linux-dmabuf-from-the-m.patch
- recipes-browser/chromium/chromium-ozone-wayland/0005-ozone-wayland-Handle-viz-process-restart.patch
- recipes-browser/chromium/chromium-ozone-wayland/0006-ozone-wayland-Move-the-host-gpu-common-and-test-code.patch
- recipes-browser/chromium/chromium-ozone-wayland/0007-Change-the-order-when-the-opaque-region-is-updated.patch
- recipes-browser/chromium/chromium-ozone-wayland/0008-Separate-swap-buffer-and-presentation-callbacks.patch
- recipes-browser/chromium/chromium-ozone-wayland/0009-Ease-the-buffer-swap-and-maintenance.patch
- recipes-browser/chromium/chromium-ozone-wayland/0010-ozone-wayland-Don-t-wait-for-frame-callback-after-su.patch
- recipes-browser/chromium/chromium-ozone-wayland/0011-ozone-wayland-Fix-presentation-feedback-flags.patch
- recipes-browser/chromium/chromium-ozone-wayland_73.0.3683.103.bb
This commit includes fixes for the performance regression and
enables the VizDisplayCompositor back.
The fix is to reduce the time spend on swap. On Rpi3 the total
swap time dropped from ~35 ms to ~13ms, which resulted in
stable FPS rate and no significant FPS drops.
> chromium-ozone-wayland: Fix regression with VizDisplayCompositor

- recipes-browser/chromium/chromium-ozone-wayland_73.0.3683.103.bb
So far, we were using Chromium's default GN path for the system
wayland-scanner binary, "/usr/bin/wayland-scanner", which may not be present
at all and which should never be used anyway. Instead, we now point to the
version built by the wayland-native recipe.
Doing so of course requires depending on wayland-native in the first place,
and that requires adding back REQUIRED_DISTRO_FEATURES and a DEPENDS block
that got removed with no explanation when the recipe was updated to
M72 (commit 97876fab, "chromium: Update to 72.0.3626.81").
Fixes #241
> chromium-ozone-wayland: Stop depending on the system's wayland-scanner binary

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-crc32c-Re-enable-crc-and-crypto-extensions-to-arm64-.patch
Currently, it fails when compiling on arm64 due to disabled crc
and crypto extensions.
> chromium: Fix arm64 build.

- recipes-browser/chromium/chromium-ozone-wayland/0001-ozone-wayland-Do-not-add-window-if-manager-does-not-.patch
- recipes-browser/chromium/chromium-ozone-wayland/0001-ozone-wayland-Fix-NativeGpuMemoryBuffers-usage.patch
- recipes-browser/chromium/chromium-ozone-wayland_74.0.3729.131.bb
This commit fixes two issues:
1) When the zwp_linux_dmabuf protocol is not available, the
WaylandConnection still has been trying to access the manager
and add a Window to it. This patch avoids this behaviour.
2) NativeGpuMemoryBuffers support was broken after a major refactoring
done. Now, it works again.
> chromium-ozone-wayland: Fix usage without zwp_linux_dmabuf and NGMB.

- recipes-browser/chromium/files/musl/musl_fix-stack.patch
- recipes-browser/chromium/files/musl/musl_no_execinfo.patch
- recipes-browser/chromium/files/musl/musl_resolver.patch
One patch musl_no_execinfo.patch needed to be forward ported and add
missing musl checks
Other two are refreshed automatically to avoid patch fuzz warnings
> chromium: Refresh musl related patches

- recipes-browser/chromium/chromium-ozone-wayland/0001-v4l2_device-Update-CanCreateEGLImageFrom-to-support-.patch
- recipes-browser/chromium/chromium-ozone-wayland_74.0.3729.157.bb
The first patch allows GpuVideoDecoder to actually get created.
Without it chrome://gpu report hardware video acceleration is
enabled, but actually ffmpegVideoDecoder is used for the decode.
The second adds NV12 & YVU420 formats for all ARM platforms,
otherwise V4L2 VDA on dragonboard will error with NV12 buffers.
Signed-off-by: Peter Griffin <peter.griffin@linaro.org>
> chromium: add 2 fixes for v4l2 VDA support

- recipes-browser/chromium/chromium-ozone-wayland/0001-Add-support-for-V4L2VDA-on-Linux.patch
This patch fixes up V4L2VDA support to add back in VP9 codec support which is now present in mainline kernel.
This was tested on db820c with venus v4l2 driver. I've also included Stanimir SoB as he is venus v4l2
driver maintainer and helped debug/fix this issue.
> Fixup v4l2 vda on Linux patch to include VP9

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/add_internal_define_armv7ve.patch
- recipes-browser/chromium/files/musl/musl_lss-match_syscalls.patch
- recipes-browser/chromium/files/musl/musl_portable_msghdr.patch
- recipes-browser/chromium/gn-native_75.0.3770.90.bb
msghdr is not same on musl and glibc but chromium assumes so
so lets fix it such that we can initialize the msghdr structure
in a clever way such that we don't have to know how its laid out
> chromium: Fix build with musl/x86_64

- dynamic-layers/rust-layer/recipes-browser/firefox/firefox_60.4.0esr.bb
I failed to build firefox without this dependency against poky:master(bc5f6725af04417dcf5c65981d8b85abee9c61d8).
> firefox: Add a missing dependency "dbus-glib"

- recipes-browser/chromium/chromium-gn.inc
The usual limit (i.e. the value returned by `ulimit -n`), 1024, is too low
for ld.bfd to be able to link the `chrome` binary.
Add a fatal check for the value that aborts when ld.bfd is being used and
the resource limit is too low.
Fixes #194.
> chromium: Check maximum number of open file descriptors when using ld.bfd

- recipes-browser/chromium/chromium-gn.inc
This was introduced in commit 0f625720 ("chromium: fix x11 dependency
brought by at-spi2-core package") but never worked; `use_atk` is an internal
GN variable that cannot be set by users. Any `do_configure` log shows that
all GN invocations show a message about how setting `use_atk` has no effect.
This is not a problem though, as it is set in Chromium by checking if
`use_x11` is true (corroborated by the fact that this argument has always
been a no-op while not breaking chromium-ozone-wayland).
> chromium: Stop passing use_atk to GN.

- recipes-browser/chromium/files/musl/musl_lss-match_syscalls.patch
Fixes
| ../../third_party/lss/linux_syscall_support.h:3557:16: error: use of undeclared identifier '__NR_stat64'
|     LSS_INLINE _syscall2(int,     stat,            const char*, f,
> chromium: Fix stat64 related build with musl

- recipes-browser/chromium/chromium-gn.inc
`bb.utils.contains()` requires both "ld-is-gold" and "ld-is-lld" to be
present in `DISTRO_FEATURES`, which in practice means the rlimit check will
happen even when one is not using ld.bfd.
Switch to `bb.utils.contains_any()`, which tests for the presence of any of
the arguments, as we originally intended.
> chromium: Use the right bb.utils call in do_check_fdlimit_for_linking

- recipes-browser/chromium/chromium-ozone-wayland/0001-ozone-wayland-Implement-CreateNativePixmapAsync.patch
- recipes-browser/chromium/chromium-ozone-wayland_77.0.3865.90.bb
Chromium may want to create native pixmaps in async way now.
The Ozone/Wayland in the current stable release did not include
the fix to allow async creation of the pixmaps, which exists in
the upstream.
Thus, backport that.
> Chromium/Wayland: Backport fix for the native gpu memory buffers.

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-WTF-Make-LinkedHashSet-understand-values-for-which-m.patch
Backports a path that fixes a renderer crash.
Issue: #313
> chromium: Backport patch to fix renderer crash.

- dynamic-layers/rust-layer/recipes-browser/firefox/firefox/fixes/Bug-1590977-openmax-Import-latest-OpenMAX-IL-1.1.2-headers.patch
- dynamic-layers/rust-layer/recipes-browser/firefox/firefox_68.0esr.bb
OpenMAX IL 1.1.2 header files were released twice on the same version,
and Firefox 68 includes the OLD headers.
The main change between the two versions is definition of fixed-sized
integers.  For example, the old version defines OMX_U32 as unsigned long,
but the new version defines it as uint32_t.
The definition of the old version is apparently wrong, because there is
no guarantee that unsigned long is 32-bit length.  Actually unsigned
long is 64-bit length on ARM64 and this mismatch cause a problem when
using OpenMAX on RZ/G2 series SoCs.
> firefox: Import latest OpenMAX IL 1.1.2 headers

- dynamic-layers/rust-layer/recipes-browser/firefox/firefox_68.0esr.bb
- recipes-browser/chromium/chromium.inc
These names follow the following cpe naming from nvd:
firefox:
https://nvd.nist.gov/products/cpe/detail/7356?keyword=firefox&status=FINAL&orderBy=CPEURI&namingFormat=2.3&startIndex=20
chromium:
https://nvd.nist.gov/products/cpe/detail/621194?keyword=chromium&status=FINAL&orderBy=CPEURI&namingFormat=2.3
https://nvd.nist.gov/products/cpe/detail/200115?keyword=chromium&status=FINAL&orderBy=CPEURI&namingFormat=2.3
Fixes: #325
> Firefox, chromium: Add CVE_PRODUCT names.

- recipes-browser/chromium/chromium-ozone-wayland/0001-ozone-wayland-Complete-submission-of-a-buffer-submit.patch
- recipes-browser/chromium/chromium-ozone-wayland_78.0.3904.108.bb
There was a corner case that resulted in a frozen rendering.
Backporting the fix.
> chromium-ozone-wayland: Fix occasional rendering freezes.

- dynamic-layers/rust-layer/recipes-browser/firefox/README.md
- dynamic-layers/rust-layer/recipes-browser/firefox/firefox/prefs/disable-e10s.js
- dynamic-layers/rust-layer/recipes-browser/firefox/firefox_68.0esr.bb
This preference isn't available as of firefox-68.
Use environment variable MOZ_FORCE_DISABLE_E10S=1 instead.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1548941
> firefox: Remove PACKAGECONFIG[disable-e10s]

- dynamic-layers/rust-layer/recipes-browser/firefox/firefox/fixes/0001-Bug-1554949-Fix-WebRTC-build-failure-with-newer-linu.patch
- dynamic-layers/rust-layer/recipes-browser/firefox/firefox_68.0esr.bb
WebRTC's code in Firefox isn't buildable against recent Linux kernel.
In addition, it can't build on some platform even if it's old kernel due to the recipe's problem.
This PR fixes these issues.
I confirmed it on zeus, not yet on master.
Because it has unresolved dependency in meta-oe (nodejs-native -> c-ares-native).
> firefox: Fix buid error of WebRTC

- recipes-browser/chromium/files/musl/musl_no_mallinfo.patch
Fixes musl patches after recemnt chromium updates
no code chanhes per se
Fixes
Applying patch musl_no_mallinfo.patch
patching file base/process/process_metrics_posix.cc
patching file base/trace_event/malloc_dump_provider.cc
Hunk #1 succeeded at 132 with fuzz 2.
patching file third_party/swiftshader/third_party/llvm-7.0/configs/linux/include/llvm/Config/config.h
patching file third_party/swiftshader/third_party/llvm-subzero/build/Linux/include/llvm/Config/config.h
patching file third_party/tcmalloc/chromium/src/config_linux.h
> chromium: Fix patch fuzz

- recipes-browser/chromium/chromium-gn.inc
Avoid warning due to the class rename in OE-Core.
Fixes:
WARNING: distro_features_check.bbclass is deprecated, please use features_check.bbclass instead
Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>
> chromium: rename distro_features_check to features_check

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0003-Fix-sandbox-Aw-snap-for-syscalls-403-and-407.patch
* All necessary background infomation is in patch added
* Fixes [1]
[1] https://github.com/OSSystems/meta-browser/issues/357
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
> chromium: Fix frequent 'Aw, snap'on 32bit systems with glibc >= 2.31

- recipes-browser/chromium/chromium.inc
If I read correctly there have been discussions about auto-generation of license entries. We might need to add files to licenses but that is not the scope of this patch. This patch is just a build fix.
> gn-native / chromium: Fix license files

- conf/layer.conf
The thud branch is no longer officially supported, and the latest updates to
the Chromium recipe have not even been tested in it.
Fixes #324.
> Remove "thud" from LAYERSERIES_COMPAT.

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/chromium.inc
- recipes-browser/chromium/files/0001-stl_util-support-older-clang.patch
Switch back to python2 and inherit setuptools instead. Also fixes
warrior build when clang 8 is used (I used newer clang when
tested the recipe before).
fixes #380 
> chromium: fix warrior build with clang 8 and inherit setuptools.

- recipes-browser/chromium/chromium-ozone-wayland_83.0.4103.116.bb
Fixes configure error with poky master branch:
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
pkgresult = exec_script(pkg_config_script, args, "value")
^----------
Current dir: /home/builder/src/yocto/poky/build/tmp/work/cortexa57-poky-linux/chromium-ozone-wayland/83.0.4103.116-r0/chromium-83.0.4103.116/out/Release/
Command: python /home/builder/src/yocto/poky/build/tmp/work/cortexa57-poky-linux/chromium-ozone-wayland/83.0.4103.116-r0/chromium-83.0.4103.116/build/config/linux/pkg-config.py atk atk-bridge-2.0
Returned 1.
stderr:
Package atk-bridge-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `atk-bridge-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'atk-bridge-2.0' found
Could not …
> chromium-ozone-wayland: add build dependency to at-spi2-atk

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-content-Avoid-calling-DeleteForCurrentDocument-from-.patch
Some clients can experience crash that happens in
ManifestManagerHost that may result in a stack with
over 99k frames!
> chromium: fix spontaneous crash in ManifestManagerHost

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-Turn-TouchMove-to-async-after-the-first-GestureScrol.patch
Some users may experience input lag with touch events.
This backport fixes this issue.
See https://crbug.com/1072364 for more details.
> chromium: fix unintended throttling of TouchMoves.

- conf/layer.conf
Chromium requires pythonnative which is in meta-python2, so we need to add this to the bowser layer dependencies. Also, layerindex only supports 25 characters so LAYERSERIES_COMPACT should be made shorter.
> Add meta-python2 to LAYERDEPENDS and shorten layer index

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-IWYU-add-includes-for-uint64_t-and-std-string.patch
Previously failing to compile sim_hash.h with error
| In file included from ../../components/federated_learning/sim_hash.cc:5:
| ../../components/federated_learning/sim_hash.h:20:15: error: unknown type name 'uint64_t'
|   void SetBit(uint64_t pos);
Patch 0001-Fix-lack-of-uint64_t-in-sim_hash-namespace.patch fixes
this error, but should be removed as soon as the chromium version
is updated to 86.x.xxxx.xx+.
> chromium: add patch to include uint64_t in sim_hash namespace

- recipes-browser/chromium/chromium.inc
When building chromium without including mime-xdg, bitbake throws the
following warning:
WARNING: chromium-x11-86.0.4240.111-r0 do_package_qa:
QA Issue: package contains desktop file with key 'MimeType' but does not inhert mime
In order to deal with this warning, have the chromium recipe inherit
the mime-xdg recipe.
Signed-off-by: Stacy Gaikovaia <stacygaikovaia@gmail.com>
> chromium: Add mime-xdg to get rid of build warning

- recipes-browser/chromium/files/remove-enable-dse-memoryssa-command-line-flag.patch
Now it applies properly without errors.
issue:
```
patch < remove-enable-dse-memoryssa-command-line-flag.patch
patching file BUILD.gn
patch: **** malformed patch at line 40: 2.25.1
```
> chromium: fix remove-enable-dse-memoryssa patch

- recipes-browser/chromium/README
- recipes-browser/chromium/chromium-gn.inc
Support for Jumbo builds was removed upstream, and M87 does not have any
code handling the argument we were passing.
> chromium: Remove the "jumbo-build" PACKAGECONFIG knob.

- recipes-browser/chromium/README
- recipes-browser/chromium/chromium-ozone-wayland_87.0.4280.141.bb
- recipes-browser/chromium/files/0001-ozone-add-va-api-support-to-wayland.patch
Not only the HWs were tested. The patch was mostly tested
with Intel Gen8 and Gen9. Also, with AMD RX460. So, bear that
in mind when you enable va-api.
In order to have it running, one must enable VA-API and
proprietary codecs in Chromium
PACKAGECONFIG_pn-chromium-ozone-wayland_append = " proprietary-codecs
use_vaapi".
> chromium: add patch that enables VA-API with ozone/wayland.

- recipes-browser/chromium/chromium-gn.inc
Since upstream [Ship ANGLE libEGL.so and libGLESv2.so on Linux stable][1]
to fix [WebGL seems to be disabled in Pixi JS on Chrome 80][2]. Do the
same thing in recipe, otherwise there was a failure when launch
chromium with command line on target raspberry pi 4:
...
sh-5.0# chromium --no-sandbox
|[3503:3503:1209/005940.666757:ERROR:gl_implementation.cc(286)]
Failed to load libGLESv2.so.2: libGLESv2.so.2: cannot open shared
object file: No such file or directory
|[3503:3503:1209/005940.676576:ERROR:viz_main_impl.cc(229)] Exiting
GPU process due to errors during initialization
...
[1] https://chromium-review.googlesource.com/c/chromium/src/+/2044054
[2] https://crbug.com/1049449)
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
> chromium: install ANGLE so files (libEGL.so, libGLESv2.so)

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-RandBytes-Stop-including-sys-random.h-on-Linux.patch
This header might not exist on systems with very old glibc packages (e.g.
CentOS 7) when building some host binaries that we need to run as part of
the build. It turns out the header is not necessary at all, as Chromium uses
LSS (Linux Syscall Support) to call the syscall and falls back to reading
from /dev/urandom when that fails.
Fixes #445.
> chromium: Backport patch to stop including <sys/random.h>

- README
This layer has dependend on the meta-python2 layer since commit
4eb1ab946 ("conf/layer.conf: Add meta-python2 to LAYERDEPENDS"), but this
was not documented in the README.
> Document meta-python2 dependency in README.

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/CVE-2021-21148.patch
A stable channel has been updated to 88.0.4324.150, but it hasn't
been rolled out yet. Thus, backport the patch and keep it until
the meta-browser chromium recipe is updated to 88.0.4324.150.
> chromium: backport patch that addresses cve-2021-21148 (0day)

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-Fix-ill-formed-C-code.patch
Thanks to Zoltán Böszörményi for pointing to the upstream fix.
Fixes #461.
> chromium: Backport upstream patch to fix the build with LLVM 12 and later

- recipes-browser/chromium/chromium-gn.inc
- recipes-browser/chromium/files/0001-link-atomic-for-target-only.patch
replaces #443 
----
When host (such as CentOS 8) did not install libatomic, there was a
link failure on native. In fact, only target requires to link atomic,
the native does not. So link atomic for target only by
(current_toolchain != host_toolchain)
Fixes #431
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
> chromium: avoid link latomic failure on CentOS 8 host

- meta-firefox/README.md
- meta-firefox/conf/layer.conf
- meta-firefox/recipes-browser/firefox/firefox/fixes/Bug-1640982-SetCARGO_PROFILE_RELEASE_LTO-true-when-e.patch
- meta-firefox/recipes-browser/firefox/firefox_68.9.0esr.bb
Depends on https://github.com/OSSystems/meta-browser/pull/470
> firefox: backport fix for newer rust and add python and python2.7 to HOSTTOOLS

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0001-mojo-Include-string.h-for-strncpy-declaration.patch
Replaces https://github.com/OSSystems/meta-browser/pull/466
> chromium: Fix build with clang 12

- meta-firefox/classes/mozilla.bbclass
- meta-firefox/conf/layer.conf
This is a hack for allow building the firefox 68esr on Centos/Fedora.
Detailed description of the problem:
https://github.com/OSSystems/meta-browser/issues/338
Signed-off-by: Lukasz Majewski <lukma@denx.de>
> firefox: Provide symbolic link for python2.7 when firefox 68esr is built

- meta-firefox/classes/mozilla.bbclass
- meta-firefox/conf/layer.conf
Reverts OSSystems/meta-browser#399
It was merged by accident, I've rebased the PR and tested it locally and it definitely doesn't work for me on Ubuntu 21.04, the errors seem the same as what I've documented in https://github.com/OSSystems/meta-browser/commit/92eee5b7f42db21e9fe460fdc92c5fcce6660e6c so it looks like this symlink doesn't really help. At this point I believe it would be better for someone interested in firefox to spend time on upgrade to newer ESR 78 where python3 should work OOTB, instead of spending even more time trying to get pythonnative working here (the python/python2.7 in HOSTTOOLS works for me for long time and now with separate layer it's not so terrible temporary work around - as only people really interested in firefox will ever include meta-firefox in …
> Revert "firefox: Provide symbolic link for python2.7 when firefox 68esr is built"

- meta-chromium/recipes-browser/chromium/files/musl/0001-mallinfo-implementation-is-glibc-specific.patch
while building for aarch64 ran into a case where HAVE_MALLINFO was
hardcoded, undefine it for musl like other places as well.
> chromium: Update mallinfo patch for aarch64

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Its well supported on arm/x86/aarch64 architectures
and is faster to link see [1]
[1] https://lld.llvm.org/#performance
> chromium: Always use LLD for linking

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0012-Fix-font-rendering-with-glibc-2.33.patch
A change in the fstat syscall in glibc-2.33
causes font rendering issues when sandbox is enabled.
https://github.com/OSSystems/meta-browser/issues/473
> Fix font rendering with glibc-2.33

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Chromium depends on virtual/libgl,
which oe-core provides by default in mesa.
opengl or vulkan is a REQUIRED_DISTRO_FEATURES for mesa.
In a minimal build of oe-core + meta-oe + meta-python2,
bitbake would complain that nothing provides
virtual/libgl, virtual/libgles2.
Also makes meta-chromium pass yocto-check-layer.
> chromium: Add opengl to REQUIRED_DISTRO_FEATURES

- meta-chromium/README.md
- meta-chromium/recipes-browser/chromium/chromium-gn.inc
This knob was added back in 2014 in commit fb6df963376c ("chromium: Add
recipe for version 37.0.2062.0"). Multithreaded rasterization was under
development back then, but this hasn't been the case since M39 and M40 (see
https://crbug.com/169282 and https://crbug.com/413479).
Given multithreaded rasterization was enabled by default in 2015, the
--enable-impl-side-painting was removed around that time and that this knob
was off by default, it should be safe to remove it altogether.
> chromium: Remove impl-side-painting PACKAGECONFIG knob.

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/musl/0009-provide-res_ninit-and-nclose-APIs-on-non-glibc-linux.patch
- meta-chromium/recipes-browser/chromium/files/musl/0020-Fix-tab-crashes-on-musl.patch
- meta-chromium/recipes-browser/chromium/files/musl/0021-pthread_getname_np.patch
Refresh existing patches to apply cleanly on latest version
Add a patch to not use pthread_getname_np when not using glibc ( like
android )
> chromium: Fix build with musl

- meta-chromium/recipes-browser/chromium/files/musl/0001-mallinfo-implementation-is-glibc-specific.patch
- meta-chromium/recipes-browser/chromium/files/musl/0006-fontconfig-Musl-does-not-have-rand_r-API.patch
- meta-chromium/recipes-browser/chromium/files/musl/0009-provide-res_ninit-and-nclose-APIs-on-non-glibc-linux.patch
These patches are musl specific and are refreshed to fix mainly the
problem with stack overflow which was happening due to crash in thread
stack from code using mallinfo, we have to disable mallinfo using
codepaths completely.
rand_r() API is available in musl so there is no need to disable it
providing res_ninit/res_nclose using obsolete APIs is not good solution
so do not use these APIs on musl
chromium works like a charm on musl now ( tested on x86_64/qemu )
> chromium: Fix tab crashes due to stack overflow on musl

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Caused loads of undefined symbols as:
| ld.lld: error: undefined symbol: std::_Rb_tree_increment(std::_Rb_tree_node_base*)
| >>> referenced by cpp_generator.cc
Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>
> chromium: Fix native build-breaking typo

- meta-chromium/recipes-browser/chromium/files/musl/0001-mallinfo-implementation-is-glibc-specific.patch
This is found when compiling for aarch64/musl
> chromium: Add missing mallifo fix for musl

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
* the limit-number-of-LTO-jobs.patch sets the default to be 8, but we can
set whatever user configured in PARALLEL_MAKE
* with "-j 64" in PARALLEL_MAKE the do_compile task is 3.8 minutes faster
(from 2701s to 2473s)
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
> chromium-gn: respect PARALLEL_MAKE when setting max_jobs_per_link

- meta-chromium/recipes-browser/chromium/chromium.inc
This reverts commit e109eb76fe2983a0e0c038d974a62eec70a23c24.
This change broke the hardknott build by preventing the libc++ headers from
being installed into the sysroot:
x86_64-poky-linux-clang++ -target x86_64-poky-linux  -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -rtlib=compiler-rt --unwindlib=libgcc -stdlib=libc++ -mlittle-endian -Qunused-arguments -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/data/src/yocto/poky/build-hardknott-intel-corei7-64/tmp/work/corei7-64-poky-linux/chromium-x11/92.0.4515.159-r0/recipe-sysroot -MMD -MF obj/v8/cppgc_base/sweeper.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE …
> Revert "chromium: Set LIBCPLUSPLUS to use libc++"

- meta-chromium/recipes-browser/chromium/chromium.inc
This should fix issue seen with
https://github.com/OSSystems/meta-browser/pull/551
Explicitly add dependency on libcxx to fix:
https://github.com/OSSystems/meta-browser/pull/556
https://github.com/OSSystems/meta-browser/pull/554
for hardknott and older.
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
> chromium: Set LIBCPLUSPLUS to use libc++

- meta-chromium/README.md
- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Chromium uses D-Bus to communicate with UPower.
It uses it to query battery among many things.
see:
services/device/battery/battery_status_manager_linux.cc
Fixes error/warning messages related to UPower:
```
Failed to call method: org.freedesktop.UPower.GetDisplayDevice
The name org.freedesktop.UPower was not provided by any .service files
```
> chromium: Add UPower to RDPENDS

- meta-chromium/README.md
- meta-chromium/conf/layer.conf
- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/chromium.inc
- meta-chromium/recipes-browser/chromium/files/0015-build-use-python3.patch
- meta-chromium/recipes-browser/chromium/gn-native_94.0.4606.61.bb
Fixes https://github.com/OSSystems/meta-browser/issues/496
If someone can run some runtime test on this PR, then it would be great, I've only build tested chromium-ozone-wayland and chromium-x11 on honister with qemux86-64.
> Switch to python3 and remove dependency on meta-python2

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
this is undefined behaviour, mant times devs used them together to get
the missing space at the beginning of string which append/prepend needs
but thats not intended behaviour
> chromium-: Do not use append with += operator

- meta-chromium/recipes-browser/chromium/files/chromium-wayland/0001-ozone-add-va-api-support-to-wayland.patch
After https://crrev.com/c/3141878, it's required to set
supports_vaapi in properties to make Wayland use va-api.
Fixes #592
> chromium-ozone-wayland: fix va-api.

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_96.0.4664.110.bb
When using a distro without "wayland" in DISTRO_FEATURES, the build
fails due to libxkbcommon being missing. Add the missing libxkbcommon
dependency, since it's required for x11 only builds too.
Signed-off-by: Robert Joslyn <robert.joslyn@redrectangle.org>
> chromium-x11: Add missing DEPENDS on libxkbcommon

- meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_96.0.4664.110.bb
- meta-chromium/recipes-browser/chromium/files/chromium-wayland/0001-ozone-wayland-fixed-terminate-caused-by-binding-to-wrong-version.patch
The Ozone/Wayland implementation had a few places where the Wayland
objects were bound without proper checking for their versions.  That was
part of the technical debt not addressed before, and ended up causing
the issue explained in the linked crbug: the compositor terminates the
client that binds to the protocol that it does not actually support.
This patch fixes the issue by adding the necessary checks in all places
where they were missing.  Also a convenience macro for validating the
version is proposed.
author	Alexander Dunaev
Backport patch to fix this issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1279574
Signed-off-by: MarkusVolk <f_l_k@t-online.de>
> chromium-ozone-wayland: fix runtime for wayland 1.20.0

- meta-chromium/conf/layer.conf
- meta-firefox/conf/layer.conf
its not going to be backward ABI compatible with honister due to variable renaming.
> layers: Bump to use kirkstone

- meta-chromium/README.md
- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Kirkstone provides gtk4 4.4.0, Chromium 97 has a configuration
setting to build with GTK version 3 or 4. Expose this choice in
PACKAGECONFIG.
Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>
> chromium: Add PACKAGECONFIG settings to switch between GTK 3/4

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
building 32bit x86 results in textrels which I guess should be fixed
so here is a workaround until they are root caused and fixed.
> chromium: Ignore textrels on x86 build

- meta-chromium/README.md
- meta-chromium/recipes-browser/chromium/chromium-gn.inc
This helps to use either system provided libc++ or bundled libc++ with
chromium. Defaults in chromium is to use bundled version, however in OE
we have used the system provided so far, therefore the default are not
changed here, just an option offered to enable custom libc++ if someone
desires so. Should we default to use the custom copy by default, perhaps
yes but thats a separate discussion
> chromium: Create packageconfig to control libc++ to use

- meta-firefox/recipes-devtools/cbindgen/cbindgen_0.8.7.bb
* fixes:
WARNING: cbindgen-native-0.8.7-r0 do_unpack: URL:
git://github.com/eqrion/cbindgen.git;protocol=https does not set any
branch parameter. The future default branch used by tools and
repositories is uncertain and we will therefore soon require this is
set in all git urls.
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
> cbindgen: add explicit branch parameter

- meta-chromium/recipes-browser/chromium/chromium.inc
- meta-chromium/recipes-browser/chromium/generate_license_list.py
This is based on an original version I wrote years ago. Specifically, its
`SKIPPED_DIRECTORIES` variable might need to be updated.
As described in the script, it uses Chromium's own tools/licenses.py script
to scan for third_party directories and license files. This means its output
is generated on a best-effort basis, as some directories are non-compliant
upstream or may not be found. It might also include directories which are
not used in a Yocto/OpenEmbedded build.
> chromium: Add a generate_license_list.py script to help generate LIC_FILES_CHKSUM.

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0014-grit-util-py-remove-deprecated-mode-for-open.patch
Signed-off-by: Markus Volk <f_l_k@t-online.de>
> tools/grit/grit/util.py: remove deprecated mode for open

- meta-chromium/recipes-browser/chromium/chromium-x11_109.0.5414.74.bb
libX11-xcb.so.1 is loaded at runtime by the X11 backend, but we had no
explicit dependency on the package that provides it (libx11-xcb).
It ended up being installed most of the time anyway, but make sure it is
listed as a runtime dependency to avoid the issue described in #683.
Fixes #683.
Signed-off-by: Raphael Kubo da Costa <raphael.kubo.da.costa@intel.com>
> chromium-x11: Add RDEPENDS on libx11-xcb.

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
As discovered by @rakuco during the discussion off #695, we missed some upstream changes to what libraries are built and installed for ANGLE and Swiftshader:
* https://chromium-review.googlesource.com/c/chromium/src/+/3380402 Removed legacy Swiftshader. We don't need to install libEGL.so and libGLESv2.so to chromium/swiftshader anymore.
* https://chromium-review.googlesource.com/c/chromium/src/+/3015696 Install libvulkan.so.1, which ANGLE needs.
* https://chromium-review.googlesource.com/c/chromium/src/+/2845811 Install Swiftshader VK files.
> chromium: incorporate upstream ANGLE and Swiftshader changes

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
The x86-32 bit target build is not supported for Chromium-x11 so do_configure fails while building x86-32 bit target but, the failure appears quite late in a build.
Removing x86-32 bit target from COMPATIBLE_MACHINE will make it fail much earlier and in clear manner if a user tries to build for an x86-32 bit target.
References:
https://groups.google.com/a/chromium.org/g/chromium-packagers/c/Q7jI7kI9umM/m/IoPYldUSCwAJ
https://support.google.com/chrome/a/answer/7100626
Error logs while building x86-32 bit target:
> | DEBUG: Python function extend_recipe_sysroot finished
> | DEBUG: Executing shell function do_configure
> | ERROR at //BUILD.gn:1641:1: Assertion failed.
> | assert(
> | ^-----
> | 'target_cpu=x86' is not supported for 'target_os=linux'. Consider omitting 'target_cpu' (default) …
> chromium: Indicate that x86-32 is not a supported machine

- meta-chromium/recipes-browser/chromium/chromium-ozone-wayland_112.0.5615.165.bb
- meta-chromium/recipes-browser/chromium/files/0009-nomerge-attribute-on-declaration-is-only-available-s.patch
- meta-chromium/recipes-browser/chromium/files/0017-Revert-Fix-std-span-autodetection-7805.patch
- meta-chromium/recipes-browser/chromium/files/0018-Only-default-operator-on-declaration.patch
- meta-chromium/recipes-browser/chromium/files/musl/no-res-ninit-nclose.patch
- meta-chromium/recipes-browser/chromium/libffi_%.bbappend
As explained in:
https://github.com/OSSystems/meta-browser/commit/2f5fe79935e1f5350f9e487625343a8f27b165d3 
Chromium doesn't allow building with system libwayland anymore, and needs (a static version of) libffi to build its own libwayland. Therefore, libffi_%.bbappend was added to make libffi_pic.a (static library) available while building chromium-ozone-wayland.
This libffi_%.bbappend is causing yocto-check-layer to give compliance error for meta-chromium layer.
By adding "use_system_libffi=true" to GN_ARGS in chromium-ozone-wayland recipe and removing the libffi_%.bbappend, we can make chromium-ozone-wayland to build with libffi.so (shared library). With these changes, we can avoid using libffi_pic.a (static library) for chromium-ozone-wayland build and also resolve yocto-check-layer …
> chromium: Make yocto-check-layer pass

- meta-chromium/README.md
This makes it easier for users to find out what they need to do to build the recipe successfully without having to read our commit messages (see e.g. #718).
While here, change the formatting we use for the headings so I can add a subheading for the dunfell instructions.
> chromium: Add dunfell instructions to README.md.

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
It turns out that Rust might be used in the build in 114 already. As discussed in #723, we need to figure out how to best support Rust builds, and until we've done so we need to disable it.
> chromium: Disable Rust for now

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
We have required clang 14 since the update to Chromium 115, so make sure the version check reflects this and points people to the right branch.
> chromium: Require clang 14.0.0 in do_check_llvm_version()

- meta-chromium/conf/layer.conf
- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0023-Use-the-correct-path-to-libclang_rt.builtins.a.patch
- meta-chromium/recipes-browser/chromium/files/0024-Adjust-the-Rust-build-to-our-needs.patch
- meta-chromium/recipes-browser/chromium/files/0025-Make-toolchain_supports_rust_thin_lto-configurable.patch
- meta-chromium/recipes-browser/chromium/files/backport/Make-toolchain_supports_rust_thin_lto-configurable.patch
- meta-chromium/recipes-browser/chromium/gn-utils.inc
- meta-chromium/recipes-browser/chromium/rust_%.bbappend
This adds a dependency on OE's Rust recipe, as well as all the necessary changes to make Chromium successfully use that toolchain.
This change will also mean we don't support any Yocto release older than kirkstone, as that is the first release with Rust in OE that isn't EOL yet. Most notably, we will drop support for dunfell.
> chromium: Enable Rust

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
https://crrev.com/c/4210955 made `enable_js_type_check` Ash-only, so we don't need to set it so `false` any more.
License changes:
----------------
None.
Test-built:
-----------
* chromium-ozone-wayland:
- nanbield, clang, MACHINE=qemuarm64
> chromium: Remove `enable_js_type_check=false` GN arg

- meta-chromium/README.md
- Remove dunfell-specific notes now that dunfell is unsupported.
- Link to chromiumdash.appspot.com, as OmahaProxy has been retired.
> meta-browser: Update some README.md information

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0019-Don-t-require-profiler_builtins.rlib.patch
Backport `0019-Don-t-require-profiler_builtins.rlib.patch` from master branch.
This fixes Chromium compilation errors, when using `meta-lts-mixins` layer with latest revision from `kirkstone/rust` branch (Rust 1.75).
> kirkstone: chromium: Don't require profiler_builtins.rlib

- meta-chromium/recipes-browser/chromium/gn-native_122.0.6261.128.bb
- meta-chromium/recipes-browser/chromium/gn/gn-bootstrap-Don-t-pass-removed-dupbuild-ninja-optio.patch
Add one backported patch to fix a build error on Yocto master.
License changes:
----------------
Added licenses: none.
Removed licenses: none.
Updated licenses: none.
Test-built:
-----------
* chromium-x11:
- master, clang, MACHINE=qemuarm
> chromium: Fix gn build for Yocto master

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Replace all usages off `RECIPE_SYSROOT` and `RECIPE_SYSROOT_NATIVE` with the respective matching `STAGING_*` variables to ensure compatibility with all build setups.
License changes:
----------------
Added licenses: none.
Removed licenses: none.
Updated licenses: none.
Test-built:
-----------
* chromium-wayland:
- nanbield, clang, MACHINE=qemuarm64
> chromium: Use STAGING_* dirs instead of RECIPE_SYSROOT(_NATIVE)

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/backport/Add-missing-components-enterprise-buildflag.patch
Fixes #811.
Add one backported patch to fix a build race condition that would sometimes lead to build errors.
License changes:
----------------
Added licenses: none.
Removed licenses: none.
Updated licenses: none.
Test-built:
-----------
* chromium-wayland:
- nanbield, clang, MACHINE=qemuarm64
* chromium-x11:
- master, clang,   MACHINE=qemuarm
> chromium: Fix build race condition

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0009-Adjust-the-Rust-build-to-our-needs.patch
- meta-chromium/recipes-browser/chromium/libstd-rs_%.bbappend
- meta-chromium/recipes-browser/chromium/rust_%.bbappend
Fixes #792.
In #782, we decided to depend on rust instead of libstd-rs, because the latter didn't include libprofiler_builtins and also used a naming scheme that trips up Chromium.
However, in #791 we decided to patch Chromium so that it doesn't need libprofiler_builtins any more, because the master version of the rust recipe also doesn't include it.
Finally, while investigating #792 it turned out that our approach breaks as soon as we have something that depends on libstd-rs in our dependency graph. In that scenario, both libstd-rs and rust (the latter due to our bbappend file) install Rust libraries to /usr/lib/rustlib. This first leads to Chromium build system errors (due to libstd-rs's naming scheme), and after fixing these to Rust …
> chromium: Depend on libstd-rs instead of rust

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Fixes #794.
We previously created a symlink pointing to the subdirectory of the latest version under $STAGING_LIBDIR_NATIVE/clang, and then copied the libclang_rt.builtins library from $STAGING_LIBDIR/clang to the same directory as the native library. This is necessary because we need to point Chromium to a single clang directory for building both native and target code, and we need its path to be independent of the specific clang version used.
However, the chosen approach leads to an error when doing a build, updating meta-clang to a revision containing a new version of clang, and then doing an incremental build.
This commit replaces the previous approach with a more safe one that does a full copy of the $STAGING_LIBDIR_NATIVE/clang …
> chromium: Fix incremental build error after meta-clang update

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/backport/NewTabPage-Add-missing-dep-to-cr_components.patch
Dependency is missing in NewTabPage module. This can cause random build errors. Error occurrence depends on the order in which packages were build. It seems to occur more frequently with lower BB_NUMBER_THREADS values.
Build failed in my case usually with following error:
```
Error: Could not load gen/ui/webui/resources/tsc/cr_components/history_clusters/history_clusters_shared_style.css.js (imported by gen/chrome/browser/resources/new_tab_page/tsc/modules/history_clusters/suggest_tile.js): ENOENT: no such file or directory, open 'gen/ui/webui/resources/tsc/cr_components/history_clusters/history_clusters_shared_style.css.js'
```
This issue most likely occurs also on master (Chromium 122 at the moment of writing), because fix was merged in version 125. I experienced this problem only on …
> chromium: Backport missing dependency in NewTabPage

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Due to commit [clang: use nonarch_libdir/clang for all runtime files][1] applied, the clang runtime libraries was installed to ${nonarch_libdir}, no matter the value of libdir
Tweak it for do_copy_clang_library, use ${nonarch_libdir} to instead
[1] https://github.com/kraj/meta-clang/commit/cda1376a97b86d6ae5c92fd931f9583430c73885
> chromium: fix do_copy_clang_library failed for multilib

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
As mentioned in e.g. #849, `--use-gl=egl` doesn't work any more. We can replace it with `--use-gl=angle --use-angle=gles-egl`, or just `--use-angle=gles-egl` as ANGLE is the default.
> chromium: Update EGL CLI args

- meta-chromium/README.md
- meta-chromium/recipes-browser/chromium/files/0002-v8-qemu-wrapper.patch
- meta-chromium/recipes-browser/chromium/files/0003-wrapper-extra-flags.patch
- meta-chromium/recipes-browser/chromium/gn/0001-Pass-no-static-libstdc-to-gen.py.patch
My affiliation has changed 🎉 Update my contact information in the README.md
as well as in the patches that have my Signed-off-by tag.
> chromium: Update my email address in the repository

- meta-chromium/conf/layer.conf
Fixes #862.
Thanks to @darren-etheridge for finding this as well as the right name to use!
> [scarthgap] chromium: Use correct Rust mixin layer dependency

- .github/workflows/yocto_matrix.yml
Beside the manual trigger, also enable the pull request trigger.
Differentiate between the manual and PR triggering when determining the URLs and branches to be able to use both kind of triggers.
This commit is currently also present in my master branch for Firefox 137.0.2 PR, but I needed it for some quick tests only . It will be removed from there, and the idea is that the force-push will trigger this workflow (hopefully) after git rebase.
(If you are familiar with github workflow, feel free to go through this in details... so far I only used these workflows in my own repo only, so there is some trial and error on my end)
> firefox: enable pull_request trigger for github workflow

- .github/workflows/yocto_matrix.yml
The test reporting github action fails to upload the test results with the following error:
`HttpError: Resource not accessible by integration`
I am not really sure why it started this - I have used exactly the same permissions in my repository for months. Based on some issues I have found in the repository of the action, it requires write permission to some new properties of the repository. However considering that it used to work with the current permissions for a long time, this makes uncomfortable granting anything new - hence I'd rather bid farewell to this, and maybe look for an alternative in the future.
The tests are still executed though, and their overall status is still reported as the status of the job. This is only about the test report artifact.
> firefox: remove test reporting from the workflow

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
Add configuration options to enable hardware video decoding using stateless V4L2 M2M device. This allows offloading e.g. h264 video playback to Hantro VPU on i.MX8MP where this was tested. To make that work, enable `use-v4l2` and `proprietary-codecs` PACKAGECONFIG.
For i.MX8MP the following additional udev rules are mandatory:
```
SUBSYSTEM=="video4linux", ATTR{name}=="nxp,imx8mm-vpu-g1-dec", SYMLINK+="video-dec%n"
SUBSYSTEM=="video4linux", ATTR{name}=="nxp,imx8mm-vpu-g2-dec", SYMLINK+="video-dec%n"
SUBSYSTEM=="media", ATTR{model}=="hantro-vpu", SYMLINK+="media-dec%n"
```
This commit was implemented with much great help from Jianfeng Liu .
> chromium: Add v4l2 m2m stateless decode configuration options

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0020-rust-filter-out-arm-specific-flags-from-rust-compile.patch
- meta-chromium/recipes-browser/chromium/files/0021-chromium-fix-v4l2-compiler-error-on-arm.patch
This pull request adds two new patches to the Chromium build for ARM platforms, addressing build and compiler errors specific to ARM architectures. The main changes include filtering out unsupported ARM-specific flags from Rust compiler arguments and fixing a narrowing conversion error in the V4L2 video decoder backend. Additionally, debug flags are removed for ARM builds to prevent linker errors due to large binary sizes.
ARM-specific build and compiler fixes:
* Added `0020-rust-filter-out-arm-specific-flags-from-rust-compile.patch` to filter out `-mbranch-protection` and `-mfpu=` flags from Rust compiler arguments, which are not supported on non-ARM architectures. (`meta-chromium/recipes-browser/chromium/chromium-gn.inc`, `meta-chromium/recipes-browser/chromium/files/0020-rust-filter-out …
> chromium: Fix compile errors on arm32 architecture

- meta-chromium/recipes-browser/chromium/chromium-gn.inc
- meta-chromium/recipes-browser/chromium/files/0016-Fix-adler-reference-for-Rust-1.86-and-later.patch
Rust 1.86 ships adler2, so the library name has to be adjusted accordingly.
Fixes #909
> scarthgap: chromium: Fix build with Rust >= 1.86
